export const DEFAULT_READ_LIMIT = 500
export const MAX_LINE_LENGTH = 2000
export const DEFAULT_MAX_BUFFER_LINES = 50_000
export const PERFORMANCE_MEASURE_LIMIT = 100
export const DEFAULT_TERMINAL_COLS = 80
export const DEFAULT_TERMINAL_ROWS = 24
